import { Inter } from 'next/font/google';

import { Sidebar } from '@/components/sidebar';
import { Content } from '@/components/content';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Sidebar />
        <Content>{children}</Content>
      </body>
    </html>
  );
}
